name: integration-tests

on: [push, pull_request]

jobs:
  setup_bare_project:
    name: Setup Bare Remix Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun Runtime
        uses: xhyrom/setup-bun@v0.1.8
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test test/integration/create-remix-app/index.test.ts
